dist: trusty
sudo: false
addons:
  apt:
    packages:
    - libtinfo-dev
language: c
compiler: clang
script:
- cd $TRAVIS_BUILD_DIR
- curl -L https://github.com/erlang/otp/archive/OTP-19.2.tar.gz | tar xz
- ls -l
- cd otp-OTP*
- ./otp_build autoconf
- ./otp_build --enable-bootstrap-only
- ./otp_build boot
- ./otp_build remove_prebuilt_files
- ./otp_build configure --without-termcap --enable-m64-build --enable-hipe --without-javac --enable-builtin-zlib --disable-saved-compile-time --enable-native-libs
- ./otp_build boot -a
- ./otp_build release -a $TRAVIS_BUILD_DIR/otp
- ls -l $TRAVIS_BUILD_DIR/otp
- cd $TRAVIS_BUILD_DIR && tar cfz otp.tar.gz otp
deploy:
  provider: releases
  api_key:
    secure: 
  file: emacs.tar.gz
  skip_cleanup: true
  on:
    tags: true
