dist: xenial
sudo: false
language: c
compiler: clang
script:
- cd $TRAVIS_BUILD_DIR
- curl -L https://github.com/erlang/otp/archive/OTP-21.1.4.tar.gz| tar xz
- curl -L https://github.com/openssl/openssl/archive/OpenSSL_1_1_1a.tar.gz | tar xz
- cd $TRAVIS_BUILD_DIR/openssl-OpenSSL*
- ./config --prefix=$TRAVIS_BUILD_DIR/ssl no-deprecated no-comp no-shared no-tests no-threads no-ui
- make prefix=$TRAVIS_BUILD_DIR/ssl install
- ls -l $TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR/otp-OTP*
- ./otp_build autoconf
- ./otp_build configure --with-ssl=$TRAVIS_BUILD_DIR/ssl --without-termcap --enable-m64-build --without-javac --enable-builtin-zlib --enable-native-libs --disable-saved-compile-time 
- ./otp_build boot -a
- ./otp_build release -a $TRAVIS_BUILD_DIR/otp
- ls -l $TRAVIS_BUILD_DIR/otp
- cd $TRAVIS_BUILD_DIR && tar cfz otp.tar.gz otp
deploy:
  provider: releases
  api_key:
    secure: Xs0hI1lpsruXw5+BeozPbVMPHVD4JIcWwL5n2qXUjkdUN0CG0yMDuASFbP+ltYR9D4zkWTBI57+GBHt15N3MWAwlMe1OURSOFfzzUHZKpRXKUM24CbNHjIolAKkTNd7atseDBuurEjzCTt1Bd1hTYZV3GgpbWfV6et29fi2QWt15ehLVReOdYfkVNIkcY5a5cSzyVkKYZLed8yQNzqkInNM7Y8qMgmwm3xE2w9SsCUtx7UXlNw2wGQvoFPqY1quWvnBKRQUqzO/JkjWRuzKGZhrwqPj0dOiEyk97kE8AWcrAqaxk1wVSDu1OcoqAFNR/xyI1ZU+jOyLxZkXC6EqotxCnA+FlhVdDAPQe9cwYzj50bOLw5UM2W2QGmqVy89A/ZzmLZKBkhfyksll1W+AdIhdDKj/527UzMhEAgmGIfDoJNERGH3vbhx+9furmijUppH5ps2M0LCTnUsp0zt4f8pht/r+O11q6pY4IhlVP8mMDUux+uKzEkcIqz/X2xFMURqK84hFcVjXAFRIfS2XbcDmabLkujjrcEjx4671/0yhlSBkBlrQ659b9ahQPZU8s6ZJF4FdSiR0OsRW1DepZEgTIwjdJ5W6m09vjkm6Ueba+QAUY5qPN27oQkMTWppdBP3/Sqmi2DqKhf3VDxc3IKrRN8nvz3TsuaUCnlOsRUyA=
  file: otp.tar.gz
  skip_cleanup: true
  on:
    repo: henglinli/build-otp
    tags: true
